services:
  sat:
    build:
      context: .
      dockerfile: Dockerfile.sat
    networks:
      - network1
    ports:
      - "5001:5001"

  sat2:
    build:
      context: .
      dockerfile: Dockerfile.sat
    networks:
      - network1
    ports:
      - "5002:5001"

  gs:
    build:
      context: .
      dockerfile: Dockerfile.gs
    networks:
      - network1
    ports:
      - "5000:5000"


networks:
  network1:
    name: VirtualSatNet
